name: dart_orm
version: 0.2.1
description: >
  Easy-to-use and easy-to-setup database ORM for dart.
author: Ustimenko Sergey <ustims@gmail.com>
homepage: https://github.com/ustims/DartORM
dev_dependencies:
  test: '^0.12.5'
  dart_orm_adapter_postgresql: '^0.1.0'
  dart_orm_adapter_mongodb: '^0.1.3'
  dart_orm_adapter_mysql: '^0.1.4'
