name: dart_orm
version: 0.0.2
description: >
  Easy-to-use and easy-to-setup database ORM for dart.
author: Ustimenko Sergey <ustims@gmail.com>
homepage: https://github.com/ustims/DartORM
dependencies:
  postgresql: any